# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

def pods_func
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    pod 'MKBaseClassesSDK', :git => 'http://gitlab.txooo.cc/HuangYibo/MKBaseClassesSDK'
    pod 'CTMediator'
end

target 'MainProject' do
  
  # Pods for MainProject
  pods_func

  target 'MainProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MainProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
