# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject
  pod 'SnapKit', '~> 4.0.1'
  pod 'RxSwift', '~> 4.3.1'
  pod 'RxCocoa', '~> 4.3.1'
#  pod 'ReactiveSwift'
  pod 'ReactiveCocoa'
  pod 'Alamofire', '~> 4.7.3'
  pod 'Kingfisher', '~> 4.10.0'
  pod 'ObjectMapper', '~> 3.3.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  target 'SwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
