# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'KiwiBDD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KiwiBDD
  
  target 'KiwiBDDTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Kiwi', '~> 3.0.0'
  end

  target 'KiwiBDDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
