# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
# The bundle identifier of your app
app_identifier ENV['APP_IDENTIFIER'] 
# your Apple ID user
username ENV['APPLE_ID'] 

# 元数据的路径
metadata_path ENV['METADATA_PATH']
screenshots_path ENV['SCREENSHOTS_PATH']

 #App store 中待发布的 App 版本，若每个 target 的版本号不同，可以通过.env 文件来分别定义
 # app_version ENV['APP_VERSION_RELEASE']

 #下载 metadata 及 screenshots 时直接覆盖，不询问
 force true

 #不覆盖 iTunes Connect原有截图
 skip_screenshots true
    
 #自动提交审核
 submit_for_review ENV['SUBMIT_FOR_REVIEW']
  
 #审核通过后立刻发布
 automatic_release ENV['AUTOMATIC_RELEASE']

 #新版本修改记录
 release_notes({        
    "zh-Hans" => ENV['RELEASE_NOTES']
 })

#App 加密算法使用情况及广告相关配置
submission_information({
    #Export Compliance
    export_compliance_available_on_french_store: "false",
    export_compliance_contains_proprietary_cryptography: "false",
    export_compliance_contains_third_party_cryptography: "false",
    export_compliance_is_exempt: "false",
    export_compliance_uses_encryption: "false",
    export_compliance_app_type: nil,
    export_compliance_encryption_updated: "false",
    export_compliance_compliance_required: "false",
    export_compliance_platform: "ios",

    content_rights_contains_third_party_content: "false",
    content_rights_has_rights: "false",

    #Advertising Identifier
    add_id_info_limits_tracking: "false",
    add_id_info_serves_ads: "false",
    add_id_info_tracks_action: "false",
    add_id_info_tracks_install: "false",
    add_id_info_uses_idfa: "false"
});