# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFuncDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CFuncDemo
  pod 'libffi-iOS', :path => "./libffi-iOS.podspec"
  target 'CFuncDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CFuncDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
