use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MixSDK_Example' do
  pod 'MixSDK', :path => '../'

  target 'MixSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
