# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LottieDemo
  pod 'lottie-ios'
  
  target 'LottieDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
